### ISSUE TITLE
Can it be used on normal linux system

### ISSUE THREAD

**Issue by MCM-Mike** [AliShahram/RFID-Library-Management-System#2]
I would be interested if you project could also be run under a normal Linux environment without having an Arduino.
Would this be possible? 
 
possible secret key exposure or is it just a test key? ; https://github.com/AliShahram/RFID-Library-Management-System/blob/master/Capstone_Project/settings.py

**Comment by AliShahram** [comment]
Yes, you can run the project without Arduino- I am using Arduino just to send the RFID tag information to the system when scanned. It mostly depends on the type of RFID reader; if it can connect to wifi their won't be need for the Arduino.
