### ISSUE TITLE
Arduino RFID not working

### ISSUE THREAD

**Issue by ahmedtsadek** [AliShahram/RFID-Library-Management-System#8]
Hi I tried to run the whole code on my Linux system and it starts successfully but the RFID tag does nothing and doesn't fill anything
I tried Arduino MFRC522 examples
readAndwrite
read personal data
can you please help me making the rfid works?
I have Arduino Nano with RFID-RC522
also I can work on Linux, Macos, windows

**Comment by AliShahram** [comment]
Hi, 
What type of RFID tags are you using? I would make sure that the RFID tags are compatible with the RFID reader. Does the reader register the tags? It would usually flash or beep if it registers the tag.

**Comment by ahmedtsadek** [comment]
Hi,
Thanks for helping me. I am using RFID-RC522 with arduino nano And It usually comes with a RFID card tag and key fob tag having 1KB memory.
Should i setup the arduino to read and write or read personal data or just read the serial?

**Comment by AliShahram** [comment]
I am sorry for the late reply. Were you able to make it work?
Any of those options should work, the RFID device will only be used for reading the tags.
